class IdmError(ValueError):
    code: str

class XmlError(IdmError): ...
class PathError(IdmError): ...
class SchemaError(IdmError): ...
class JsonError(IdmError): ...
class CardinalityError(IdmError): ...
class ContentModelError(IdmError): ...
class EncodingError(IdmError): ...
class IdmIoError(IdmError): ...

class Document:
    root_name: str
    namespace: str | None
    @staticmethod
    def parse(xml: str) -> Document: ...
    @staticmethod
    def parse_bytes(bytes: bytes) -> tuple[Document, str]: ...
    @staticmethod
    def new(full_title: str, idm_code: str) -> Document: ...
    @staticmethod
    def from_json(value: str) -> Document: ...
    def copy(self) -> Document: ...
    def to_xml(self, pretty: bool = ...) -> str: ...
    def to_bytes(self, pretty: bool = ..., encoding: str = ...) -> bytes: ...
    def to_json(self, pretty: bool = ...) -> str: ...
    def validate_json(self) -> str: ...
    def count(self, name: str) -> int: ...
    def element_paths(self, name: str) -> list[str]: ...
    def find_by_guid(self, guid: str) -> list[str]: ...
    def find_by_id(self, id: str) -> list[str]: ...
    def path_of(self, locator: str) -> str: ...
    def text(self, path: str) -> str: ...
    def set_text(self, path: str, value: str) -> None: ...
    def set_text_unchecked(self, path: str, value: str) -> None: ...
    def attribute(self, path: str, name: str) -> str: ...
    def set_attribute(self, path: str, name: str, value: str) -> None: ...
    def remove_attribute(self, path: str, name: str) -> None: ...
    def add_schema_attribute(self, path: str, name: str) -> str: ...
    def attributes_json(self, path: str) -> str: ...
    def attribute_slots_json(self, path: str) -> str: ...
    def node_info_json(self, path: str) -> str: ...
    def schema_rule_json(self, path: str) -> str: ...
    def element_json(self, path: str) -> str: ...
    def append_schema_child(self, parent_path: str, name: str) -> str: ...
    def insert_schema_child(self, parent_path: str, name: str, position: int) -> str: ...
    def remove_schema_node(self, path: str) -> None: ...
    def duplicate_schema_node(self, path: str) -> str: ...
    def move_schema_node(self, path: str, target_path: str, after: bool) -> str: ...
    def reparent_schema_node(
        self, path: str, new_parent_path: str, position: int | None = ...
    ) -> str: ...
    def paste_schema_node_json(
        self, parent_path: str, element_json: str, position: int | None = ...
    ) -> str: ...
    def allowed_children_json(self, parent_path: str) -> str: ...
    def apply_json(self, edit_json: str) -> str: ...
    def apply_batch_json(self, batch_json: str) -> str: ...
    def diff_json(self, other: Document) -> str: ...

def schema_catalog_json() -> str: ...
def read_schema_text(schema_dir: str, name: str) -> str: ...
def verify_schema_dir_json(schema_dir: str) -> str: ...
